Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -18,5 +18,15 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Run Docker container
+        id: run_docker
         run: |
           docker run --entrypoint appbuild.sh bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
+        continue-on-error: true
+
+      - name: Check GTest results
+        run: |
+          docker_exit_code=$(docker inspect -f '{{.State.ExitCode}}' $(docker ps -aq --filter ancestor=bakcyl/paragon_back))
+          if [ $docker_exit_code -ne 0 ]; then
+            echo "GTest failed! Docker container exited with code $docker_exit_code."
+            exit 1
+          fi
