Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -2,11 +2,7 @@ name: C/C++ CI
 
 on:
   push:
-    branches:
-      - '*'
   pull_request:
-    branches:
-      - '*'
 
 jobs:
   build:
@@ -17,15 +13,14 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Run Docker container
-        id: run_docker
         run: |
-          docker run --entrypoint appbuild.sh -e "REPO=${{ vars.REPO }}" -e "BRANCH=${{ github.head_ref }}" --name paragonTestBuild bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
+          docker run --entrypoint appbuild.sh -e "REPO=${{ github.repository }}" -e "BRANCH=${{ github.ref_name }}" --name paragonTestBuild bakcyl/paragon_back:${{ env.DOCKER_IMAGE_VERSION }}
         continue-on-error: true
 
       - name: Check build results
         run: |
-          exit `docker logs paragonTestBuild 2>&1 | grep -iE "Error" | wc -l`
+          exit $(docker logs paragonTestBuild 2>&1 | grep -iE "Error" | wc -l)
 
       - name: Check GTest results
         run: |
-          exit `docker logs paragonTestBuild 2>&1 | grep Failed | grep "Test \#" | wc -l`
+          exit $(docker logs paragonTestBuild 2>&1 | grep Failed | grep "Test #" | wc -l)
